### ISSUE TITLE
ToDo 1 спринт

### ISSUE THREAD

**Issue by podolskijspace** [podolskijspace/middle.messenger.praktikum.yandex#3]
- [ ] Добавить страницы ошибок
- [ ] Добавить изменение аватара
- [ ] Настройки пользователя доделать
- [ ] Команда для запуска npm run start  на порту 3000
